### ISSUE TITLE
Provide options for non-US names

### ISSUE THREAD

**Issue by lmullen** [ropensci/gender#14]
The package currently only uses US names. It would be good to be able to use names from non-US places, especially if  the data is historical as with the SSA or IPUMS data. 

This might be possible using these data sets:

- [IPUMS International](https://international.ipums.org/international/)
- [North Atlantic Population Project](https://www.nappdata.org/napp/)

**Comment by kinow** [comment]
+1 I can help looking for Brazilian Portuguese names

**Comment by lmullen** [comment]
@kinow That would be great; thanks. I'm planning a release in the next couple weeks.
