### ISSUE TITLE
Long Processing Time for Large List of Names

### ISSUE THREAD

**Issue by jtribbia** [ropensci/gender#19]
I’m using the gender package to predict the gender of a list of customers based on the first name in the shipping address. So far, it has performed well on a small subset of our customer list. But, I’m running into very long processing times when I’m running it against a full list of qualified customers (~2 million). 
 
 Have you encountered this before? If so, I was wondering if you have any suggestions to improve the process time on such a large list of names?

**Comment by lmullen** [comment]
@jtribbia: The gender package is not especially speedy. It is possible that there are performance improvements to be gained, but I'm unlikely to pursue them in the near future.

The simplest thing to do is to perform as few calls to gender as possible. I assume you have a lot of duplicate names in your data set. If you use `dplyr` to get a list of unique names (or of unique combinations of names and birth years), you can really cut down on the number of computations.

Here's a quick example of how that would work:

```
library("dplyr")

names <- sample(c("john", "jane", "sue", "barack"), 1000, replace = TRUE)
years <- sample(1960:1990, 1000, replace = TRUE)

data <- data_frame(names, years)
  
nrow(data) # 1000

data %>% 
  group_by(names, years) %>% 
  tally() %>% 
  nrow() # 124
```

And then on your reduced list you figure out the likely genders, then merge that data back into your original dataset.

**Comment by lmullen** [comment]
Now that I think more about it, it might be possible to memoise calls to `gender()`. I've added this as issue #20.

**Comment by jtribbia** [comment]
Thanks Lincoln. This was really helpful.
