### ISSUE TITLE
Dealing with NA data

### ISSUE THREAD

**Issue by albnd** [ropensci/gender#25]
The values returned when names are not contained in the database is, for example:
> gender("Lorax", years = c(1880, 2012))
Source: local data frame [0 x 6]

Variables not shown: name (chr), proportion_male (dbl), proportion_female
  (dbl), gender (lgl), year_min (dbl), year_max (dbl)

Rather than an NA, and the result doesn't get captured when, for example, searching multiple names.  Consequently, the resulting list can't be paired with the input dataset using cbind(), as they differ in length.

**Comment by lmullen** [comment]
@albnd Can you please let me know which version of gender you are using? `packageVersion("gender")` will do the trick.

**Comment by albnd** [comment]
@lmullen 0.5.0.9000

**Comment by lmullen** [comment]
You have the dev version of `gender` installed. So you're correct that the return value of the function has changed. While the dev version is not yet fully baked, it should work for what you are trying to do, but the approach to the problem has changed. Here is what you could do:

First, and easiest, you can install the current CRAN version (0.4.3) with `install.packages()`. It will return a list with a list item for every name that you search for. Names that are not found will be marked `NA`. To get a data frame, you have to do various `rbind` things. This is probably what you are expecting. Consider this example:

```
library(dplyr)
library(gender)
packageVersion("gender")
#> '0.4.3'

d <- data_frame(names = c("John", "Jane", "Lorax"))
gender(d$names)
```

That returns a list of lists:

```
[[1]]
[[1]]$name
[1] "John"

[[1]]$proportion_male
[1] 0.9961

[[1]]$proportion_female
[1] 0.0039

[[1]]$gender
[1] "male"

[[1]]$year_min
[1] 1932

[[1]]$year_max
[1] 2012


[[2]]
[[2]]$name
[1] "Jane"

[[2]]$proportion_male
[1] 0.0029

[[2]]$proportion_female
[1] 0.9971

[[2]]$gender
[1] "female"

[[2]]$year_min
[1] 1932

[[2]]$year_max
[1] 2012


[[3]]
[[3]]$name
[1] "Lorax"

[[3]]$proportion_male
[1] NA

[[3]]$proportion_female
[1] NA

[[3]]$gender
[1] NA

[[3]]$year_min
[1] 1932

[[3]]$year_max
[1] 2012

```

Second, you can use the dev version. The dev version is now much faster and much more sensibly returns a data frame. You can use this data frame with dplyr's `left_join()` (or base R `mege()`) to accomplish what you want to do. Consider this example:

```
library(dplyr)
library(gender)
packageVersion("gender")
#> '0.5.0.9000'

d <- data_frame(names = c("John", "Jane", "Lorax"))
g <- gender(d$names)
```

The return value is a data frame, with rows only for matching names. If you had duplicated names (e.g., if you searched for `Jane` twice) each name is only returned once.

```
Source: local data frame [2 x 6]

  name proportion_male proportion_female gender year_min year_max
1 Jane          0.0029            0.9971 female     1932     2012
2 John          0.9961            0.0039   male     1932     2012
```

Notice that the returned data frame contains a name column, as does our original data frame. A left join will give us the `NA`s too.

```
d %>% left_join(g, by = c("names" = "name"))
```

That returns 

```
Source: local data frame [3 x 6]

  names proportion_male proportion_female gender year_min year_max
1  John          0.9961            0.0039   male     1932     2012
2  Jane          0.0029            0.9971 female     1932     2012
3 Lorax              NA                NA     NA       NA       NA
```

Alternatively, you can use set functions to figure out which names you didn't get.

```
setdiff(d$names, g$name)
#> "Lorax"
```

See #22 for figures on the improved performance of this approach.

**Comment by albnd** [comment]
@lmullen Brilliant - thanks. And improved performance is indeed noted!  I'll close the issue.
