### ISSUE TITLE
gender() output suppresses NAs when a list of names is supplied 

### ISSUE THREAD

**Issue by dab3-2014** [ropensci/gender#26]
Hi, I'm running R version 3.1.2 on Windows 7 and download & installed the gender package from the ropensci Gitub repo ver. 0.5.0.9000. 

Here's what I'm getting:
```
> gender(tolower(c("welfram", "Wolfram", "ikea", "dominic")),c(1990,2000))
Source: local data frame [2 x 6]

     name proportion_male proportion_female gender year_min year_max
1 dominic          0.9879            0.0121   male     1990     2000
2    ikea          0.0000            1.0000 female     1990     2000
```
So there's no "NA" returned for the first entry, which is not consistent with what is mentioned on help file. Any ideas to fix this?

Thanks.

**Comment by trinker** [comment]
I think this is the same issue: https://github.com/ropensci/gender/issues/25#issuecomment-92403510  

@lmullen can confirm.

**Comment by lmullen** [comment]
You have the development version. Please see #25 for an explanation of the changes. Feel free to reopen this issue if you notice specific mismatches between the documentation and the functionality in the development version. 

Thanks @trinker.

**Comment by trinker** [comment]
No problem.  I appreciate the speedup with the dev version.

Just a curiosity.  2 questions.   I assume this is permanent (I've re-coded [qdap's `name2sex` function](https://github.com/trinker/qdap/blob/master/R/name2sex.R) accordingly).  Is this correct?  Do you have a CRAN push timeline for this version?

**Comment by lmullen** [comment]
@trinker: Yes, I think this will be a permanent change. The timeline is
basically whenever I can spend half a day on this, which might not be till
early May.

**Comment by dab3-2014** [comment]
Awesome! Thanks for the speedy response. Given the performance improvement in the dev build, I think I'll stick with it and left-join to get the desired output.
