### ISSUE TITLE
Variation in spellings

### ISSUE THREAD

**Issue by soodoku** [ropensci/gender#39]
Dear Lincoln,

For some people, minor variations in spelling of a name may not be as important. A similar names function may allow people to see potential variations, and then in the next step a vector of such names could be passed, and numbers pooled across those variations.

**Comment by lmullen** [comment]
This is essentially a data cleaning operation. Since it is impossible to predict what kinds of data people might have and what cleaning it might need, it is on the user to aggregate similar names.
