### ISSUE TITLE
Add caveats and specificity to documentation

### ISSUE THREAD

**Issue by Ironholds** [ropensci/gender#48]
This is an excellent package for mapping name to assigned gender but it has (fairly obviously) a few limitations - off the top of my head:

1. Because of the sources it's going to more-frequently fail on non-majoritarian names (think: immigrants, minority groups with particular naming conventions);
2. It's going to risk substantially misclassifying trans and non-binary people, particularly pre-transition people;
3. Because of the data-sources it uses (censuses, many of them from historic periods with even less trans/NB acceptance than today, birth data) it's not really IDing gender - it's IDing sex, as evidenced by the variables being 'male' and 'female'.

This doesn't mean it's not useful, obviously, there are a ton of cases in (particularly in dealing with historical, european-centred data or unconscious bias) where this is going to be a pretty accurate reflection of how people *experience* gender, but it would probably be good to contextualise the data and add caveats and specificity to the documentation around it. I've seen people using it unthinkingly with more recent datasets in a way that carries nontrivial data accuracy risks.

Opening this ticket not because I think y'all should write it (I'm happy to) but just to check you'd be okay with me proposing some tweaks and documentation changes.

**Comment by lmullen** [comment]
@Ironholds I agree with all those critiques. If I had it to do over I would try to pick a different package name, but that doesn't sound feasible. The package is at best a blunt instrument for historical research. 

We wrote a paper about this identifying more or less the same caveats that you've listed here. We've been relying on that for explanation. http://www.digitalhumanities.org/dhq/vol/9/3/000223/000223.html

What would you think if I added a paragraph about this to the README and linked out to the article for an explanation? My thought is that the README is the place most users are likely to see these caveats.

**Comment by Ironholds** [comment]
Sounds great to me! Tweaking the DESCRIPTION a tad maybe just to be more specific about what it reflects could also help?

**Comment by lmullen** [comment]
Will do soon. Thanks for the suggestion.
