### ISSUE TITLE
Error in `gender_df`: Can't combine logical and character

### ISSUE THREAD

**Issue by mark-fangzhou-xie** [ropensci/gender#61]
Thanks for this package! While using it to infer some names, I ran into the following error:

``` r
names_example <- tibble::tibble(first_names = c("zephaniah", "william"), years = c(1963, 1964))
gender::gender_df(names_example, name_col = "first_names", year_col = "years", method = "ssa")
#> Error: Can't combine `..1$gender` <logical> and `..2$gender` <character>.

gender::gender("william", years = 1964, method = "ssa")
#> # A tibble: 1 x 6
#>   name    proportion_male proportion_female gender year_min year_max
#>   <chr>             <dbl>             <dbl> <chr>     <dbl>    <dbl>
#> 1 william           0.996            0.0037 male       1964     1964
gender::gender("zephaniah", years = 1963, method = "ssa")
#> # A tibble: 0 x 6
#> # … with 6 variables: name <chr>, proportion_male <dbl>,
#> #   proportion_female <dbl>, gender <lgl>, year_min <dbl>, year_max <dbl>
```

It seems that when dealing with "william", the result is correct (meaning that "gender" column is a character); while dealing with "zephaniah", the function returns nothing and the class of "gender" column is logical. Thus, by using `gender_df` function, it throws an error of not being able to combine them.

My environment (I installed the most recent development version for both `gender` and `genderdata`:

```r
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5

other attached packages:
 [1] forcats_0.5.0   stringr_1.4.0   dplyr_1.0.0     purrr_0.3.4     readr_1.3.1     tidyr_1.0.2    
 [7] tibble_3.0.1    ggplot2_3.3.0   tidyverse_1.3.0 gender_0.5.4  
```

Thanks!

**Comment by mark-fangzhou-xie** [comment]
So after some investigation, I used the following work-around. At [line 67](https://github.com/ropensci/gender/blob/master/R/gender_df.R#L67), within the `do()` call, I added the following:`%>%  mutate(across(where(is.logical), as.character))`. So this code chunk becomes:

```r
data %>% 
  group_by(.dots = name_year_grouping) %>% 
  distinct(.keep_all = TRUE) %>% 
  group_by(.dots = year_grouping) %>% 
  do(results = gender(.[[name_col]], 
                      years = c(.[[year_col[1]]][1], 
                                .[[year_col[2]]][1]), 
                      method = method) 
     %>% mutate(across(where(is.logical), as.character))) %>% 
  do(bind_rows(.$results)) %>% 
  ungroup()
```

This will transform logical `gender` column into character `gender` column, and thus will not break later in the row-binding stage.

**Comment by lmullen** [comment]
@mark-fangzhou-xie Thanks for noticing this bug. Would you be willing to send your fix as a pull request? Ideally with a test for this particular problem.

**Comment by mark-fangzhou-xie** [comment]
I just added a PR (never done this before and I hope it works) and a test. 

This is a quick and dirty fix for this specific problem. I think the problem is more about the specific `gender` functions, e.g. `gender_ssa` etc. They may return undesired class of columns in the result dataframe whenever the name we are searching cannot be matched in the dataset. But I didn't look into the specifics and certainly hope my PR works for now.

**Comment by Sa-Singh** [comment]
Hi. I was running into the same error and was wondering if the code has indeed already been updated?
 Error: Can't combine `..1$gender` <logical> and `..6$gender` <character>.

**Comment by Chris-Larkin** [comment]
Just to add, i'm running into the same issue:

```
gender_predictions <- v_prop_scores %>% 
  filter(!is.na(first_name), !is.na(birth_date)) %>%
  distinct(first_name, birth_date) %>% 
  group_by(birth_date) %>% 
  do(results = gender(.$first_name, years = .$birth_date[1], method = "ssa")) %>% 
  do(bind_rows(.$results))
```

```
|====================================================================================|100% ~0 s remaining     Error in `bind_rows()`:
! Can't combine `..1$gender` <logical> and `..4$gender` <character>.
Backtrace:
 1. ... %>% do(bind_rows(.$results))
 3. dplyr:::do.rowwise_df(., bind_rows(.$results))
 4. dplyr:::label_output_dataframe(NULL, out, groups(.data), group_by_drop_default(.data))
 5. dplyr::bind_rows(out[[1]])
 8. vctrs::vec_rbind(!!!dots, .names_to = .id)
Error in bind_rows(out[[1]]) :
```

Using @fangzhou-xie 's solution `%>% mutate(across(where(is.logical), as.character))` worked for me, but just flagging that it may not have landed
